service: service:VLLM
name: medical
version: qwen2.5-aloe-beta-7b-50b2
bentoml_version: 1.3.19
creation_time: '2025-01-15T14:47:03.195245+00:00'
labels:
  model_name: HPAI-BSC/Qwen2.5-Aloe-Beta-7B
  openllm_alias: 8b,8b-medical
  platforms: linux
  source: https://github.com/bentoml/openllm-models/tree/main/src/vllm-chat
models: []
entry_service: medical
services:
- name: medical
  service: ''
  models:
  - tag: hpai-bsc--qwen2.5-aloe-beta-7b:779dce52c1cd3b4c9313b4f5c6a1e63f
    module: null
    creation_time: '2025-01-15T14:47:03.193714+00:00'
    registry: huggingface
    metadata:
      model_id: hpai-bsc/qwen2.5-aloe-beta-7b
      revision: 853ee78094c4e6ae096fe616fbc7b617dd78f1f5
      endpoint: https://huggingface.co
      include: null
      exclude: null
  dependencies: []
  config:
    name: medical
    resources:
      gpu: 3
      gpu_type: nvidia-rtx-3060
    traffic:
      timeout: 300
envs:
- name: HF_TOKEN
  value: ''
schema:
  name: medical
  type: service
  routes:
  - name: generate
    route: /generate
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
      title: Input
      type: object
    output:
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
  - name: generate_with_image
    route: /generate_with_image
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
        image:
          default: null
          title: Image
          format: image
          pil: true
          type: file
      title: Input
      type: object
    output:
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
spec: 1
runners: []
apis: []
docker:
  distro: debian
  python_version: '3.9'
  cuda_version: null
  env:
    HF_TOKEN: ''
  system_packages: null
  setup_script: null
  base_image: null
  dockerfile_template: null
python:
  requirements_txt: ./requirements.txt
  packages: null
  lock_packages: true
  pack_git_packages: true
  index_url: null
  no_index: null
  trusted_host: null
  find_links: null
  extra_index_url: null
  pip_args: null
  wheels: null
conda:
  environment_yml: null
  channels: null
  dependencies: null
  pip: null
