service: service:VLLM
name: deepseek
version: deepseek-r1-5421
bentoml_version: 1.3.19
creation_time: '2025-01-24T08:39:55.957459+00:00'
labels:
  model_name: deepseek-ai/DeepSeek-R1
  openllm_alias: deepseek-r1
  platforms: linux
  source: https://github.com/bentoml/openllm-models/tree/main/src/vllm-chat
models: []
entry_service: deepseek
services:
- name: deepseek
  service: ''
  models:
  - tag: deepseek-ai--deepseek-r1:4186915b32ac4f30a2cf994008675f4f
    module: null
    creation_time: '2025-01-24T08:39:55.956040+00:00'
    registry: huggingface
    metadata:
      model_id: deepseek-ai/deepseek-r1
      revision: 4dc77d4932316bdaa6f255ee7ad2ea3733a8ca23
      endpoint: https://huggingface.co
      include: null
      exclude: null
  dependencies: []
  config:
    name: deepseek
    resources:
      gpu: 3
      gpu_type: nvidia-rtx-3060
    traffic:
      timeout: 300
envs: []
schema:
  name: deepseek
  type: service
  routes:
  - name: generate
    route: /generate
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
      title: Input
      type: object
    output:
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
  - name: generate_with_image
    route: /generate_with_image
    batchable: false
    input:
      properties:
        prompt:
          default: what is this?
          title: Prompt
          type: string
        image:
          default: null
          title: Image
          format: image
          pil: true
          type: file
      title: Input
      type: object
    output:
      type: string
      is_stream: true
      media_type: text/event-stream
    is_task: false
spec: 1
runners: []
apis: []
docker:
  distro: debian
  python_version: '3.9'
  cuda_version: null
  env: null
  system_packages: null
  setup_script: null
  base_image: null
  dockerfile_template: null
python:
  requirements_txt: ./requirements.txt
  packages: null
  lock_packages: true
  pack_git_packages: true
  index_url: null
  no_index: null
  trusted_host: null
  find_links: null
  extra_index_url: null
  pip_args: null
  wheels: null
conda:
  environment_yml: null
  channels: null
  dependencies: null
  pip: null
